#!/usr/bin/env bash

set -e

if [ "$EUID" -eq 0 ]; then
  CONFIG="root.yaml"
elif [ "$(uname)" = "Darwin" ]; then
  CONFIG="mac.yaml"
else
  CONFIG="linux.yaml"
fi
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
