#!/bin/bash
# install_dependencies
# author: weiensong
# email: touer0018@gmail.com

OS_TYPE=$(uname)

if [ "$OS_TYPE" = "Darwin" ]; then
  platform='macos'
elif [ -f /etc/os-release ]; then
  . /etc/os-release
  if [ "$ID" = "ubuntu" ]; then
    platform='ubuntu'
  else
    echo "Other Linux: $NAME"
    exit 0
  fi
else
  echo "Unknown OS"
  exit 0
fi

if [ "$platform" = "ubuntu" ]; then
  sudo apt update
  sudo apt install -y \
    zsh \
    git \
    fzf \
    tmux \
    silversearcher-ag \
    git-delta \
    sway \
    swaylock \
    waybar \
    libreoffice

elif [ "$platform" = "macos" ]; then
  if ! command -v brew &>/dev/null; then
    echo "Homebrew not found, installing..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  else
    echo "Homebrew is already installed."
  fi

  brew install \
    git \
    tmux \
    fzf \
    the_silver_searcher \
    git-delta
fi

if ! command -v zsh &>/dev/null; then
  echo "Set zhs default..."
  chsh -s $(which zsh)
fi

if ! git config --global user.name &>/dev/null; then
  echo "Git configuring..."
  git config --global user.name "touero"
  git config --global user.email "touer0018@gmail.com"
  git config --global color.ui auto
  git config --global diff.tool nvimdiff
  git config --global difftool.prompt false
  git config --global sendemail.suppresscc self
  git config --global delta.navigate true
  git config --global delta.line-numbers true
  git config --global delta.side-by-side true
  git config --global delta.syntax-theme gruvbox-dark
fi

if ! command -v starship &>/dev/null; then
  echo "Starship not found, installing..."
  curl -sS https://starship.rs/install.sh | sh
fi

if ! command -v pyenv &>/dev/null; then
  echo "pyenv not found, installing..."
  curl -fsSL https://pyenv.run | bash
fi
