[mgr]
ratio = [1, 4, 3]
sort_by = "natural"
sort_translit = true
linemode = "size"
scrolloff = 200
show_syslink=false


[preview]
max_width = 720
max_height = 1280

[[fetchers]]
id = "mime"
name = "*"
run = "mime"
if = "!mime"
prio = "high"

[[preloaders]]
mime = "image/(avif|hei.|jxl|svg\\+xml)"
run = "magick"

[[preloaders]]
mime = "image/.*"
run = "image"

[[preloaders]]
mime = "video/.*"
run = "video"

[[preloaders]]
mime = "application/pdf"
run = "pdf"

[[preloaders]]
mime = "font/.*"
run = "font"

[[preloaders]]
mime = "application/vnd.ms-opentype"
run = "font"

[[previewers]]
name = ".*/"
run = "folder"
sync = true

[[previewers]]
mime = "text/.*"
run = "code"

[[previewers]]
mime = ".*/(xml|javascript|x-wine-extension-ini)"
run = "code"

[[previewers]]
mime = "application/(json|x-ndjson)"
run = "json"

[[previewers]]
mime = "image/(avif|hei.|jxl|svg\\+xml)"
run = "magick"

[[previewers]]
mime = "image/.*"
run = "image"

[[previewers]]
mime = "video/.*"
run = "video"

[[previewers]]
mime = "application/pdf"
run = "pdf"

[[previewers]]
mime = "application/(zip|gzip)"
run = "archive"

[[previewers]]
mime = "application/x-(tar|bzip.*|7z-compressed|xz|rar|iso9660-image)"
run = "archive"

[[previewers]]
mime = "font/.*"
run = "font"

[[previewers]]
mime = "application/vnd.ms-opentype"
run = "font"

[[previewers]]
mime = "inode/x-empty"
run = "empty"

[[previewers]]
name = ".*"
run = "file"
