#!/usr/bin/env sh
# @author touero
# @since 2025
# ocr: user ocr in gnome linux

FILE=$(mktemp --suffix=.png)
gnome-screenshot -a -f "$FILE"
TEXT=$(tesseract "$FILE" - -l chi_sim)
echo -n "$TEXT" | xclip -selection clipboard
rm -f "$FILE"
notify-send "Ocr result copied to clipboard" "$TEXT"
