[Metadata]
Name=gruvbox
Version=0.0.1
Author=touero
Description=simple gruvbox dark theme.

[InputPanel/ContentMargin]
Left=6
Right=6
Top=0
Bottom=0

[InputPanel/TextMargin]
Left=6
Right=6
Top=0
Bottom=0

[InputPanel/Background/Margin]
Left=6
Right=6
Top=0
Bottom=0

[InputPanel/Highlight/Margin]
Left=6
Right=6
Top=0
Bottom=0

[InputPanel/PrevPage/ClickMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel/NextPage/ClickMargin]
Left=0
Right=0
Top=0
Bottom=0

[InputPanel]
EnableBlur=False
NormalColor=#ebdbb2
HighlightCandidateColor=#282828
HighlightColor=#282828
HighlightBackgroundColor=#282828
Spacing=0

[InputPanel/Highlight]
Color=#d79921

[InputPanel/Background]
Color=#282828
