# -*- conf -*-
# $HOME/.config/foot/foot.ini
# @author: weiensong(touero) <touer0018@gmail.com>
# @since: 2025, 2026

include=~/.config/foot/key_bindings.ini
include=~/.config/foot/colors-dark.ini
include=~/.config/foot/colors-light.ini

[main]
font=Iosevka Nerd Font Mono:size=13
font-bold=Iosevka Nerd Font Mono:style=Bold:size=13
font-italic=Iosevka Nerd Font Mono:style=Italic:size=13
font-bold-italic=Iosevka Nerd Font Mono:style=Bold Italic:size=13
font-size-adjustment=0.85

dpi-aware=yes

[cursor]
style=beam
blink=yes

[scrollback]
lines=16384

[url]
launch=xdg-open ${url}
