# -*- conf -*-
# $HOME/.config/foot/keybinding.ini
# @author: weiensong(touero) <touer0018@gmail.com>
# @since: 2025, 2026

[key-bindings]
scrollback-up-half-page=Control+k
scrollback-down-half-page=Control+j

scrollback-up-page=Control+Shift+k
scrollback-down-page=Control+Shift+j

font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract

show-urls-launch=Control+Shift+o
show-urls-copy=Control+Shift+y

spawn-terminal=Control+Shift+M
search-start=Control+slash

[search-bindings]
delete-to-end=none

find-prev=Control+p
find-next=Control+n
extend-char=Control+l
extend-backward-char=Control+h
extend-line-down=Control+j
extend-line-up=Control+k
extend-to-word-boundary=Control+w
commit=Return
