[mgr]
ratio = [2, 2, 4]
sort_by = "natural"
sort_translit = false
linemode = "size"
scrolloff = 2
show_symlink = false
show_hidden = true

[preview]
max_width = 720
max_height = 1280
image_filter = "nearest"

[plugin]

prepend_preloaders = [
    { url = "*.svg", run = "noop" },
]

prepend_previewers = [
    { url = "*.svg", run = "code" },
]

