#Location: ~/.config/starship.toml
#What_is_starship: https://starship.rs/

add_newline = true
command_timeout = 2000

format = """$env_var$os$username$hostname$kubernetes$directory$git_branch$git_status$python
$character
"""

[character]
success_symbol = "╰⎯"
error_symbol = "╰⎯"

[env_var]
symbol = "╭╴"
variable = 'SHELL'
format = "$symbol"
disabled = false

[os]
format = '[$symbol](fg:#fabd2f) '   
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'
Unknown = '󰠥'

[username]
style_user = 'fg:#fabd2f bold'
style_root = 'fg:#cc241d bold'
format = '[//](fg:#928374) [$user](fg:#fabd2f) '
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[//](fg:#928374) [$hostname](fg:#83a598 bold) '
disabled = true

[directory]
truncation_length = 0
truncation_symbol = '…/'
home_symbol = '~'
read_only = '  '
format = '[//](fg:#928374) [$path]($style)[$read_only]($read_only_style) '
style = 'fg:#83a598'

[git_branch]
symbol = ' '
format = '[//](fg:#928374) [$symbol\[$branch\]]($style) '
style = 'fg:#b8bb26 bold'

[git_status]
disabled = true
format = '[ $all_status $ahead_behind]($style) '
style = 'fg:#b8bb26 bold'
conflicted = '🏳'
up_to_date = ''
untracked = ' '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = ' '
modified = ' '
staged = '[++\($count\)](fg:#b8bb26)'
renamed = '襁 '
deleted = ' '

[kubernetes]
format = 'via [󱃾 $context\($namespace\)](fg:#d3869b bold) '
disabled = false

[vagrant]
disabled = true

[docker_context]
disabled = true

[helm]
disabled = true

[python]
symbol = '󰌠'
python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']
format = '[//](fg:#928374) [${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '
style = 'fg:#fabd2f'

[nodejs]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true
